### ISSUE TITLE
thumbnail undefined

### ISSUE THREAD

**Issue by iSyn** [iSyn/Tsundoku#1]
@gittheking, @jasonseminara, @trevorpreston, @rapala61, @irwintsay
![screen shot 2016-10-28 at 3 53 42 pm](https://cloud.githubusercontent.com/assets/8594833/19820272/9f8afba6-9d26-11e6-9c1f-2ae5275b721a.png)

I'm assuming the error i'm having here is that some images don't have a thumbnail which ends up breaking my application.

I tried adding a `if (books.whatevergoeshere.thumbnail) do this` but nothing changes.

Thanks!

**Comment by iSyn** [comment]
Hovering over div not displaying hidden text properly

**Comment by gittheking** [comment]
@iSyn, that means that `imageLinks` is undefined. If you're going to wrap it in an `if` it will have to be `if (book.volumeInfo.imageLinks) { //do something }`.
